server:
  port: 8050
spring:
  application:
    name:Parcial-Compiladores
  datasource:
    url: jdbc:postgresql://localhost:5432/parcial_compi
    username: postgres
    password: Sebasadmin123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: always
        continue-on-error: false